namespaces = [
'ai-agents-namespace-alpha ',
'ai-agents-namespace-beta',
'all-models',
'avrcloud',
'calico-apiserver',
'calico-system ',
'cassandra-avr ',
'chess-engine-service',
'common',
'danswer ',
'default ',
'embeddings',
'face-recognition-service',
'global-search-ns',
'gpu-operator',
'haproxy ',
'harbor',
'ingress-nginx ',
'ingress-nginx-internal',
'kube-node-lease ',
'kube-public ',
'kube-system ',
'kubernetes-dashboard',
'llm-service-self',
'metallb-system',
'mongodb ',
'mongodb-avr ',
'monitoring',
'newrelic',
'nvidia-gpu-operator ',
'overleaf',
'paperless ',
'postgressql-avr ',
'redis-avr ',
'social-media-agent-live ',
'srs-ns',
'temp',
'text-to-speech-ns ',
'tigera-operator ',
]