FROM ghcr.io/joeferner/redis-commander:latest

# Set default environment variables
ENV REDIS_LABEL=RenderRedis
ENV REDIS_HOST=oregon-redis.render.com
ENV REDIS_PORT=6379
ENV REDIS_USERNAME="red-crfeunjgbbvc73c3kcqg"
ENV REDIS_PASSWORD="HZzTcTCEFYRaxBMc2zUgvE4UxmbpoE0Z"

# Expose the necessary port
EXPOSE 8081