FROM ghcr.io/joeferner/redis-commander:latest

# Set default environment variables
ENV REDIS_LABEL=Render
ENV REDIS_HOST_RENDER=oregon-redis.render.com
ENV REDIS_PORT=6379
ENV REDIS_USERNAME_RENDER=red-crfeunjgbbvc73c3kcqg
ENV REDIS_PASSWORD_RENDER=HZzTcTCEFYRaxBMc2zUgvE4UxmbpoE0Z

# Expose the necessary port
EXPOSE 8081