FROM ghcr.io/joeferner/redis-commander:latest

# Set default environment variables
ENV REDIS_LABEL=Render
# ENV REDIS_HOST=your_default_host
# ENV REDIS_USERNAME=your_default_username
# ENV REDIS_PASSWORD=your_default_password
# ENV REDIS_TLS=true

# Expose the necessary port
EXPOSE 8081